site_name: Основи на програмирането с Python
####Navigation####
nav:
    - Начало: index.md
    - Въведение: intro.md
    - Цели на Python: purpose.md
    - Още: more.md
    - Инсталиране: install.md
    - Среди за разработка: ides.md
    - Синтаксис: syntax.md
    - Помощ: help.md
    - Запазени думи: keywords.md
    - Коментари: comments.md
    - Променливи: variables.md
    - Вход и Изход: io.md
    - Числа: numbers.md
    - Стрингове: strings.md
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
theme:
    name: material
    palette:
        - scheme: default
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode
    features:
        - navigation.top

