name: Publish the GitHub Page
on:
  workflow_dispatch:
    inputs:
      Confirm:
        description: 'Are you sure you want to run:'
        required: true
        default: 'Yes'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: site-source
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force --remote-branch master
